blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Discussions
    url: https://github.com/nayandas69/linkinbio-nextjs/discussions
    about: Ask questions and discuss ideas with the community
  - name: ğŸ“§ Email Support
    url: mailto:nayanchandradas@hotmail.com
    about: Contact the maintainer directly for private matters
  - name: ğŸ¦ Github
    url: https://github.com/nayandas69
    about: Follow for updates and quick questions
  - name: ğŸ«° Patreon
    url: https://www.patreon.com/nayandas69
    about: Support the project and get exclusive content
